#############################################################################
# Makefile for building: DoNotDisturbMode
# Generated by qmake (2.01a) (Qt 4.7.4) on: ?? ?? 11 15:25:51 2012
# Project:  DoNotDisturbMode.pro
# Template: subdirs
# Command: d:/qtsdk/madde/targets/harmattan_10.2011.34-1/bin/qmake.exe -spec ../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/default -unix -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc -o Makefile DoNotDisturbMode.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = d:/qtsdk/madde/targets/harmattan_10.2011.34-1/bin/qmake.exe
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-Daemon \
		sub-DoNotDisturb

Daemon/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) Daemon/ || $(MKDIR) Daemon/ 
	cd Daemon/ && $(QMAKE) d:/studio/Github/DoNotDisturbMode/Daemon/Daemon.pro -spec ../../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/default -unix -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc -o $(MAKEFILE)
sub-Daemon-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) Daemon/ || $(MKDIR) Daemon/ 
	cd Daemon/ && $(QMAKE) d:/studio/Github/DoNotDisturbMode/Daemon/Daemon.pro -spec ../../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/default -unix -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc -o $(MAKEFILE)
sub-Daemon: Daemon/$(MAKEFILE) FORCE
	cd Daemon/ && $(MAKE) -f $(MAKEFILE)
sub-Daemon-make_default: Daemon/$(MAKEFILE) FORCE
	cd Daemon/ && $(MAKE) -f $(MAKEFILE) 
sub-Daemon-make_first: Daemon/$(MAKEFILE) FORCE
	cd Daemon/ && $(MAKE) -f $(MAKEFILE) first
sub-Daemon-all: Daemon/$(MAKEFILE) FORCE
	cd Daemon/ && $(MAKE) -f $(MAKEFILE) all
sub-Daemon-clean: Daemon/$(MAKEFILE) FORCE
	cd Daemon/ && $(MAKE) -f $(MAKEFILE) clean
sub-Daemon-distclean: Daemon/$(MAKEFILE) FORCE
	cd Daemon/ && $(MAKE) -f $(MAKEFILE) distclean
sub-Daemon-install_subtargets: Daemon/$(MAKEFILE) FORCE
	cd Daemon/ && $(MAKE) -f $(MAKEFILE) install
sub-Daemon-uninstall_subtargets: Daemon/$(MAKEFILE) FORCE
	cd Daemon/ && $(MAKE) -f $(MAKEFILE) uninstall
DoNotDisturb/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) DoNotDisturb/ || $(MKDIR) DoNotDisturb/ 
	cd DoNotDisturb/ && $(QMAKE) d:/studio/Github/DoNotDisturbMode/DoNotDisturb/DoNotDisturb.pro -spec ../../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/default -unix -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc -o $(MAKEFILE)
sub-DoNotDisturb-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) DoNotDisturb/ || $(MKDIR) DoNotDisturb/ 
	cd DoNotDisturb/ && $(QMAKE) d:/studio/Github/DoNotDisturbMode/DoNotDisturb/DoNotDisturb.pro -spec ../../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/default -unix -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc -o $(MAKEFILE)
sub-DoNotDisturb: DoNotDisturb/$(MAKEFILE) FORCE
	cd DoNotDisturb/ && $(MAKE) -f $(MAKEFILE)
sub-DoNotDisturb-make_default: DoNotDisturb/$(MAKEFILE) FORCE
	cd DoNotDisturb/ && $(MAKE) -f $(MAKEFILE) 
sub-DoNotDisturb-make_first: DoNotDisturb/$(MAKEFILE) FORCE
	cd DoNotDisturb/ && $(MAKE) -f $(MAKEFILE) first
sub-DoNotDisturb-all: DoNotDisturb/$(MAKEFILE) FORCE
	cd DoNotDisturb/ && $(MAKE) -f $(MAKEFILE) all
sub-DoNotDisturb-clean: DoNotDisturb/$(MAKEFILE) FORCE
	cd DoNotDisturb/ && $(MAKE) -f $(MAKEFILE) clean
sub-DoNotDisturb-distclean: DoNotDisturb/$(MAKEFILE) FORCE
	cd DoNotDisturb/ && $(MAKE) -f $(MAKEFILE) distclean
sub-DoNotDisturb-install_subtargets: DoNotDisturb/$(MAKEFILE) FORCE
	cd DoNotDisturb/ && $(MAKE) -f $(MAKEFILE) install
sub-DoNotDisturb-uninstall_subtargets: DoNotDisturb/$(MAKEFILE) FORCE
	cd DoNotDisturb/ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: DoNotDisturbMode.pro  ../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/default/qmake.conf ../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/g++.conf \
		../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/unix.conf \
		../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/linux.conf \
		../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/qconfig.pri \
		../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt_functions.prf \
		../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt_config.prf \
		../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/default_pre.prf \
		../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/release.prf \
		../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/default_post.prf \
		../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/warn_on.prf \
		../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt.prf \
		../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/unix/thread.prf \
		../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/moc.prf \
		../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/resources.prf \
		../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/uic.prf \
		../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/yacc.prf \
		../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/lex.prf
	$(QMAKE) -spec ../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/default -unix -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc -o Makefile DoNotDisturbMode.pro
../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/g++.conf:
../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/unix.conf:
../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/linux.conf:
../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/qconfig.pri:
../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt_functions.prf:
../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt_config.prf:
../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/default_pre.prf:
../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/release.prf:
../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/default_post.prf:
../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/warn_on.prf:
../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt.prf:
../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/unix/thread.prf:
../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/moc.prf:
../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/resources.prf:
../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/uic.prf:
../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/yacc.prf:
../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/lex.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -spec ../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/default -unix -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc -o Makefile DoNotDisturbMode.pro

qmake_all: sub-Daemon-qmake_all sub-DoNotDisturb-qmake_all FORCE

make_default: sub-Daemon-make_default sub-DoNotDisturb-make_default FORCE
make_first: sub-Daemon-make_first sub-DoNotDisturb-make_first FORCE
all: sub-Daemon-all sub-DoNotDisturb-all FORCE
clean: sub-Daemon-clean sub-DoNotDisturb-clean FORCE
distclean: sub-Daemon-distclean sub-DoNotDisturb-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-Daemon-install_subtargets sub-DoNotDisturb-install_subtargets FORCE
uninstall_subtargets: sub-Daemon-uninstall_subtargets sub-DoNotDisturb-uninstall_subtargets FORCE

sub-Daemon-check: Daemon/$(MAKEFILE)
	cd Daemon/ && $(MAKE) check
sub-DoNotDisturb-check: DoNotDisturb/$(MAKEFILE)
	cd DoNotDisturb/ && $(MAKE) check
check: sub-Daemon-check sub-DoNotDisturb-check

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

